language: node_js
node_js:
  - "8"

before_install:
    - node --version
    - npm --version
    # setting the path for phantom.js 2.0.0
install:
    - cd backend
    - npm install
    - cd ..
    - cd frontend
    - npm install
    - cd ..
script:
    - cd backend
    - npm test
    - cd ..
    - cd frontend
    - npm test
    - cd ..