---
version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
    - 27017:27017
    volumes:
    - mongodbdata:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME
    - MONGO_INITDB_ROOT_PASSWORD
    - MONGO_INITDB_DATABASE
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '1'
  backend:
    build: "./backend"
    ports:
    - 8081:8080
    environment:
    - MONGODB_USERNAME
    - MONGODB_PASSWORD
    - MONGODB_HOST
    - MONGODB_PORT
    - MONGODB_DATABASE
    - MONGODB_COLLECTION

    - EMAIL_ADDRESS
    - EMAIL_NAME
    - EMAIL_PASSWORD
    - ADMIN_EMAIL_ADDRESS

    - OAUTH2_CLIENT_ID
    - OAUTH2_CLIENT_SECRET
    - OAUTH2_REFRESH_TOKEN
    - OAUTH2_ACCESS_TOKEN
    
    - RECAPTCHA_SITE_KEY
    - RECAPTCHA_SECRET_KEY
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '1'
  frontend:
    build: "./frontend"
    ports:
    - 8080:8080
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '1'
  proxy:
    build: "./proxy"
    ports:
    - 80:80
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: '1'
volumes:
  mongodbdata:
